### ISSUE TITLE
Salt Seed (for root password salt)

### ISSUE THREAD

**Issue by orblivion** [lbryio/wallet-sync-server#2]
# Main idea

Based on [this](https://docs.standardnotes.com/specification/encryption/) from Standard Notes. Specifically, see [here](https://docs.standardnotes.com/specification/encryption/#root-key-derivation-flow---specifics).

The premise is that the server isn't to be trusted with our secrets. We want a salt on the client side, along with the _root password_, to be used as inputs to generate our encryption key and the sync server password. We need that salt to be shared between all clients.

We don't want the server to be in charge of generating the salt lest it give us a predictable salt. The Standard Notes solution (which I don't _fully_ understand, but we'll ask an auditor about it later) is to combine our identifier (email address in our case) with a client-generated nonce "seed" to generate our salt. The server is in charge of distributing the seed to the user's other clients. (My first thought is that this is as dangerous as trusting the server with generating the salt in the first place, but perhaps the use of email address here sufficiently mitigates those dangers. And yet somehow email address isn't good enough on its own. This is the part I need to sort out. I digress.).

# Domains

Our system allows for a user to switch between sync servers. (and maybe Standard Notes has the same consideration). We don't want to share sync server passwords between servers (not a huge issue since data is encrypted, but not ideal, probably). We thought about adding Domain to the input to the salt input to deal with this. However, if we just generate a new salt seed for each registration, it'll be different for each domain. But, we have to make sure that the clients do this.

# Tasks

## Server

- [x] Get Seed public endpoint
- [x] Require seed on account creation 
- [x] New salt seed when changing domains or changing password (almost done)

## Client

- [x] Implement salt seed generation on test client
- [x] Make sure email is normalized before being used as input.

## Deployment

- [x] Update code, delete database (not production yet so we don't care)

## Notes for auditor

Just to leave in the comments.

- [x] Confirm that salt seed covers the inter-domain issue
- [x] Confirm that we should generate a new salt seed on password change
- [x] Ask how this system exactly works, and if we're doing it right given that we don't understand it. Email address isn't sufficient for a secure salt, but it _is_ sufficient to keep the server from lying to us about passing the salt between clients? Is that the idea?

**Comment by orblivion** [comment]
@lyoshenka Should I close these issues myself? Just finished this.

**Comment by lyoshenka** [comment]
yea, you can close em yourself. you never have to wait for me. feel free to open/update/close issues any way you want
